apiVersion: v2
name: planka
description: Planka, the Trello clone.

type: application
version: 1.0.0

dependencies:
  - name: planka
    version: 1.0.1
    repository: "file://../submodules/planka/charts/planka"

