apiVersion: v2
name: planka
description: Planka, the Trello clone.

type: application
version: 0.1.0

appVersion: "1.25.1"

dependencies:
  - name: planka
    version: 0.2.22
    repository: "file://../submodules/planka/charts/planka"
