apiVersion: v1
kind: PersistentVolume
metadata:
  name: lubelogger-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/loot/services/lubelogger"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-data
  namespace: lubelogger
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

