apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotosocial-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/loot/services/gotosocial"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-config
  namespace: gotosocial
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

