apiVersion: v2
name: planka
description: Planka, the Trello clone.

type: application
version: 1.2.2

dependencies:
  - name: planka
    version: 2.1.0
    repository: https://plankanban.github.io/planka

