apiVersion: v1
data:
  nextcloud-password: REPLCEME
  nextcloud-username: REPLACEME
  smtp-host: REPLACEME
  smtp-password: REPLACEME
  smtp-username: REPLACEME
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
type: Opaque
---
apiVersion: v1
data:
  db-hostname: REPLACEME
  db-name: REPLACEME 
  db-password: REPLACEME
  db-username: REPLACEME
kind: Secret
metadata:
  name: nextcloud-db-creds
  namespace: nextcloud
type: Opaque

