nextcloud:
  
  replicaCount: 1

  nextcloud:
    host: cloud.anthonymag.net

    existingSecret:
      enabled: true
      secretName: nextcloud
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password

    trustedDomains:
      - cloud.anthonymag.net
      - sanji1
      - sanji1.home.arpa
      - sanji2
      - sanji2.home.arpa
      - sanji3
      - sanji3.home.arpa
  
    hooks:
      pre-installation:
      post-installation:
      pre-upgrade:
      post-upgrade:
      before-starting:
  
    ## Strategy used to replace old pods
    ## IMPORTANT: use with care, it is suggested to leave as that for upgrade purposes
    ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    strategy:
      type: Recreate
      # type: RollingUpdate
      # rollingUpdate:
      #   maxSurge: 1
      #   maxUnavailable: 0
  
    # TODO: remove after PR is merged: https://github.com/nextcloud/helm/pull/752
    extraInitContainers: 
      - name: init-redis-session-ini
        image: mirror.gcr.io/alpine:latest
        command: ['touch', '/usr/local/etc/php/conf.d/redis-session.ini']
        volumeMounts:
          - name: php-confd
            mountPath: "/usr/local/etc/php/conf.d"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
  
    # TODO: remove after PR is merged: https://github.com/nextcloud/helm/pull/752
    extraVolumes:
      - name: php-confd
        emptyDir: {}
      - name: tmpfs
        emptyDir: {}
    extraVolumeMounts:
      - name: php-confd
        mountPath: "/usr/local/etc/php/conf.d/redis-session.ini"
        subPath: redis-session.ini
      - name: tmpfs
        mountPath: "/tmp"

    securityContext: 
      runAsUser: 1000
      runAsGroup: 1000

  collabora:
    enabled: true
  
  internalDatabase:
    enabled: false
  
  externalDatabase:
    enabled: true
  
    type: postgresql
  
    existingSecret:
      enabled: true
      secretName: nextcloud-db
      usernameKey: db-username
      passwordKey: db-password
      hostKey: db-hostname
      databaseKey: db-name
  
  externalRedis:
    enabled: false
  
    ## Redis host
    host: ""
  
    ## Redis port
    port: "6379"
  
    ## Redis password
    password: ""
  
    ## Use a existing secret
    existingSecret:
      enabled: false
      # secretName: nameofsecret
      passwordKey: redis-password
  
  redis:
    enabled: true
    auth:
      existingSecret: nextcloud-cache
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: true
        #existingClaim: nextcloud-cache
    replica:
      replicaCount: 0
      #persistence:
        #enabled: true
        #existingClaim: nextcloud-cache
  
  cronjob:
    enabled: true
  
    type: cronjob
  
    # Note: crond requires root
    sidecar:
      securityContext: 
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  
    # Note: can run as non-root user. Should run as same user as the Nextcloud pod.
    cronjob:
      # Use a CronJob instead of crond sidecar container
      # crond does not work when not running as root user
      # Note: requires `persistence.enabled=true`
      schedule: "*/5 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  
  service:
    type: NodePort
    port: 80
  
  persistence:
    enabled: true
    existingClaim: nextcloud-services
  
    nextcloudData:
      enabled: true
      existingClaim: nextcloud-data
  
  nodeSelector:
    class: sanji
  
