immich:

  controllers:
    main:
      containers:
        main:
          env:
            REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
            IMMICH_MACHINE_LEARNING_URL: 'http://svc.home.arpa:3003'

  immich:
    metrics:
      # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
      enabled: false
    persistence:
      library:
        existingClaim: immich-library

  machine-learning:
    # turned off until I can mount the GPU to a kubernetes node; for now it's running on the Docker node with the iGPU
    enabled: false

  valkey:
    enabled: true
    persistence:
      data:
        enabled: true
        size: 1Gi
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce

  server:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              tag: v2.6.3
            env:
                DB_DATABASE_NAME: immich
                DB_HOSTNAME: 
                  valueFrom:
                    secretKeyRef:
                      name: immich-db
                      key: db-hostname
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db
                      key: db-username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db
                      key: db-password

  service:
    main:
      type: NodePort

